name: Build and deploy on push

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout development branch
      uses: actions/checkout@v4
    - name: Build and deploy website
      uses: shalzz/zola-deploy-action@v0.20.0
      env:
        PAGES_BRANCH: gh-pages
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
